name: Check files with Prettier

on:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        name: Configure npm caching
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/prettier.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Run prettier
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check ./resources/views
